#!/usr/bin/env bash
# This looks like its generated by AI, but I completely made it myself, I had many syntax and logic problems and let AI fix them, so this is an AI script but based and still completly the same.

set -o errexit
set -o nounset
set -o pipefail

HOME_DIR="${HOME:-/root}"

XM_DIR="$HOME_DIR/xmrig"
SRC_DIR="$XM_DIR/xmrig-src"
BUILD_DIR="$SRC_DIR/build"

BUILT_BIN="$BUILD_DIR/xmrig"

DEFAULT_POOL="gulf.moneroocean.stream:10001"
DONATION_WALLET="46m4SDFpigNZBLVUTWDhAjaMQFAMtwJkZTz4Gmy4rnhU733fwqzSDK4CeDbpFWW5ZCipJSwoTscMxHE6Wufy9odmMrVgPEC.Linux"

cd "$HOME_DIR"

clear

# ============================================
# Detect existing compiled binary
# ============================================

if [ -x "$BUILT_BIN" ]; then
  echo "Existing compiled xmrig build detected."
  echo ""

  read -r -p "Use existing compiled version instead of recompiling? (y/n): " reuse_answer

  if [[ "${reuse_answer,,}" == "y" || "${reuse_answer,,}" == "yes" ]]; then
    reuse_existing=true
  else
    reuse_existing=false
  fi
else
  reuse_existing=false
fi

# ============================================
# Build from source if needed
# ============================================

if ! $reuse_existing; then
  echo "Building xmrig from source..."

  echo ""
  echo "(1/7) Installing build dependencies..."

  sudo apt update >/dev/null 2>&1 || true

  sudo apt install -y \
    git \
    build-essential \
    cmake \
    automake \
    libtool \
    autoconf \
    libuv1-dev \
    libssl-dev \
    libhwloc-dev >/dev/null 2>&1

  echo ""
  echo "(2/7) Preparing source directory..."

  # Remove old source tree only if rebuilding
  rm -rf "$XM_DIR"

  mkdir -p "$XM_DIR"
  cd "$XM_DIR"

  echo ""
  echo "(3/7) Cloning xmrig source..."

  git clone https://github.com/xmrig/xmrig.git xmrig-src >/dev/null 2>&1 || {
    echo "Git clone failed."
    exit 1
  }

  cd "$SRC_DIR"

  echo ""
  echo "(4/7) Configuring build..."

  mkdir -p build
  cd build

  cmake .. >/dev/null 2>&1 || {
    echo "CMake configuration failed."
    exit 1
  }

  echo ""
  echo "Build completed successfully."

  echo ""
  echo "(5/7) Enabling MSR support..."

  # Install kmod if modprobe is missing
  if ! command -v modprobe >/dev/null 2>&1; then
    echo "modprobe not found. Installing kmod..."

    sudo apt install -y kmod >/dev/null 2>&1 || {
      echo "Failed to install kmod. Continuing without MSR support..."
    }
  fi

  # Try loading msr module
  if command -v modprobe >/dev/null 2>&1; then
    if sudo modprobe msr >/dev/null 2>&1; then
      echo "MSR module loaded successfully."

      # Try enabling access permissions
      sudo chmod o+w /dev/cpu/*/msr 2>/dev/null || true

      # Verify MSR device exists
      if ls /dev/cpu/*/msr >/dev/null 2>&1; then
        echo "MSR devices detected."
      else
        echo "MSR module loaded, but no MSR devices found."
      fi
    else
      echo "Could not load MSR module. Continuing anyway..."
    fi
  else
    echo "modprobe still unavailable. Skipping MSR setup."
  fi
  echo ""
  echo "(6/7) Setting up performance mode..."

  sudo apt install linux-cpupower -y >/dev/null 2>&1 || true

  if sudo cpupower frequency-set -g performance >/dev/null 2>&1; then
    echo "Performance governor enabled."

    if ls /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor >/dev/null 2>&1; then
      sudo cat /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor
    fi
  else
    echo "Could not enable performance mode. Continuing anyway..."
  fi

  echo ""
  echo "(7/7) Compiling xmrig (this may take a while)..."

  read -r -p "Press enter to continue..."

  make -j"$(nproc)" || {
    echo "Compilation failed."
    exit 1
  }

fi

# ============================================
# Verify binary exists
# ============================================

if [ ! -x "$BUILT_BIN" ]; then
  echo "Compiled binary not found at:"
  echo "$BUILT_BIN"
  exit 1
fi

# ============================================
# Wallet / pool configuration
# ============================================

echo ""
read -r -p "Do you want to donate to me? (y/n): " donate_answer

if [[ "${donate_answer,,}" == "y" || "${donate_answer,,}" == "yes" ]]; then
  echo "Thank you so much!"

  read -r -p "Enter worker name (example: Laptop01): " worker_name

  pool="$DEFAULT_POOL"

  if [ -n "$worker_name" ]; then
    wallet="${DONATION_WALLET}.${worker_name}"
  else
    wallet="$DONATION_WALLET"
  fi
else
  echo ""
  echo "There will be 3 questions so you can begin mining..."

  read -r -p "What's the pool address and port? (example: pool.example:3333): " pool

  read -r -p "What is your wallet address?: " base_wallet

  read -r -p "Enter worker name (example: Rig01): " worker_name

  if [ -n "$worker_name" ]; then
    wallet="${base_wallet}.${worker_name}"
  else
    wallet="$base_wallet"
  fi
fi

# ============================================
# Start xmrig
# ============================================

echo "Starting xmrig..."
clear
sudo "$BUILT_BIN" \
  -a rx/0 \
  --randomx-1gb-pages \
  --huge-pages \
  -o "$pool" \
  -u "$wallet" \
  -p x
