#!/usr/bin/env bash
# This looks like its generated by AI, but I completly made it myself, I had many syntax and logic problems and let AI fix them, so this is a AI script but based and still completly the same.

set -o errexit
set -o nounset
set -o pipefail

HOME_DIR="${HOME:-/root}"
XM_DIR="$HOME_DIR/xmrig"
PRECOMPILED_URL="https://raw.githubusercontent.com/Niam3231/monero-miner/refs/heads/main/linux/precompiled-arm.zip"
DEFAULT_POOL="gulf.moneroocean.stream:10128"
DONATION_WALLET="46m4SDFpigNZBLVUTWDhAjaMQFAMtwJkZTz4Gmy4rnhU733fwqzSDK4CeDbpFWW5ZCipJSwoTscMxHE6Wufy9odmMrVgPEC.Linux"

cd "$HOME_DIR"

# clean old directory if present
rm -rf "$XM_DIR"

clear
read -r -p "Do you want to use the precompiled version? Only say no if the precompiled version does not work. (y/n): " answer1
case "${answer1,,}" in
  y|yes)
    use_precompiled=true
    ;;
  *)
    use_precompiled=false
    ;;
esac

if $use_precompiled; then
  echo ""
  echo "(1/3) Installing required packages..."
  sudo apt update >/dev/null 2>&1 || true
  sudo apt install -y zip unzip curl >/dev/null 2>&1 || {
    echo "Failed to install required packages. Aborting precompiled path."
    use_precompiled=false
  }

  if $use_precompiled; then
    echo ""
    echo "(2/3) Downloading compiled version..."
    mkdir -p "$XM_DIR"
    cd "$XM_DIR"
    # follow redirects
    if ! curl -fL -o precompiled-arm.zip "$PRECOMPILED_URL"; then
      echo "Download failed. Will fall back to building from source."
      use_precompiled=false
    else
      echo "(3/3) Extracting and configuring..."
      unzip -o precompiled-arm.zip >/dev/null 2>&1 || {
        echo "Failed to unzip precompiled package. Will fall back to building from source."
        use_precompiled=false
      }
      rm -f precompiled-arm.zip
      # the precompiled binary is expected to be named xmrig
      if [ -f ./xmrig ]; then
        chmod +x ./xmrig || true
      else
        echo "Expected ./xmrig binary not found after extraction. Falling back to build."
        use_precompiled=false
      fi
    fi
  fi

  if $use_precompiled; then
    echo ""
    read -r -p "Do you want to donate to me? (y/n): " answer2
    if [[ "${answer2,,}" == "y" || "${answer2,,}" == "yes" ]]; then
      echo "Thank you so much!"
      read -r -p "Press enter to continue..."
      pool="$DEFAULT_POOL"
      wallet="$DONATION_WALLET"
    else
      echo "There will be 2 questions so you can begin to mine..."
      read -r -p "What's the pool address and port? (example: pool.example:3333) : " pool
      read -r -p "What is your wallet address? : " wallet
    fi

    echo "Starting precompiled xmrig..."
    # If this command succeeds (it will normally run until stopped), script won't continue.
    exec ./xmrig -a rx/0 -o "$pool" -u "$wallet" -p x || {
      echo "xmrig failed to start using the precompiled binary. Falling back to building from source."
      use_precompiled=false
    }
  fi
fi

# If we reach here, either user opted out of precompiled or something failed.
echo ""
echo "Proceeding to compile xmrig from source..."

echo "(1/5) Installing build dependencies..."
sudo apt update >/dev/null 2>&1 || true
sudo apt install -y git build-essential cmake libuv1-dev libssl-dev libhwloc-dev >/dev/null 2>&1

echo "(2/5) Cloning xmrig source..."
mkdir -p "$XM_DIR"
cd "$XM_DIR"
# clone into $XM_DIR/xmrig-src to avoid clobbering anything
git clone https://github.com/xmrig/xmrig.git xmrig-src >/dev/null 2>&1 || {
  echo "Git clone failed. Aborting."
  exit 1
}
cd xmrig-src

echo "(3/5) Creating build directory..."
mkdir -p build
cd build

echo "(4/5) Running cmake..."
cmake .. >/dev/null 2>&1

echo "(5/5) Compiling (this can take a while)..."
read -r -p "Press enter to continue..."
make -j"$(nproc)"

echo "Build finished."

# built binary location
BUILT_BIN="./xmrig"

if [ ! -x "$BUILT_BIN" ]; then
  echo "Built binary not found at $BUILT_BIN. Aborting."
  exit 1
fi

echo ""
read -r -p "Do you want to donate to me? (y/n): " donate_after_build
if [[ "${donate_after_build,,}" == "y" || "${donate_after_build,,}" == "yes" ]]; then
  echo "Thank you so much!"
  pool="$DEFAULT_POOL"
  wallet="$DONATION_WALLET"
else
  echo "There will be 2 questions so you can begin to mine..."
  read -r -p "What's the pool address and port? (example: pool.example:3333) : " pool
  read -r -p "What is your wallet address? : " wallet
fi

echo "Starting compiled xmrig..."
exec "$BUILT_BIN" -a rx/0 -o "$pool" -u "$wallet" -p x